/**
 * 
 */
package com.mbt.plugins;

import static org.mybatis.generator.internal.util.StringUtility.stringHasValue;

import java.util.List;

import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.Interface;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.Parameter;
import org.mybatis.generator.api.dom.java.TopLevelClass;
import org.mybatis.generator.api.dom.xml.Attribute;
import org.mybatis.generator.api.dom.xml.Document;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.config.MergeConstants;

/**
 * @author zoro02.lin
 *
 */
public class AddMysqlPaginationPlugins extends PluginAdapter {

	private static final FullyQualifiedJavaType integerType = new FullyQualifiedJavaType("java.lang.Integer");
	
	/* (non-Javadoc)
	 * @see org.mybatis.generator.api.Plugin#validate(java.util.List)
	 */
	@Override
	public boolean validate(List<String> warnings) {
		return true;
	}
	
	public boolean clientGenerated(Interface interfaze, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
		//add select pagination
		Method selectByExampleByPagination = new Method();
		
		introspectedTable.getBaseRecordType();
		
		FullyQualifiedJavaType exampleType = new FullyQualifiedJavaType(introspectedTable.getExampleType());
		FullyQualifiedJavaType baseRecordType = new FullyQualifiedJavaType(introspectedTable.getBaseRecordType());
		
		Parameter example = new Parameter(exampleType, "example");
		example.addAnnotation("@Param(\"example\")");
		Parameter startRow = new Parameter(integerType, "startRow");
		startRow.addAnnotation("@Param(\"startRow\")");
		Parameter endRow = new Parameter(integerType, "endRow");
		endRow.addAnnotation("@Param(\"endRow\")");
		selectByExampleByPagination.addParameter(example);
		selectByExampleByPagination.addParameter(startRow);
		selectByExampleByPagination.addParameter(endRow);
		selectByExampleByPagination.setName("selectByExampleByPagination");
		FullyQualifiedJavaType listType = new FullyQualifiedJavaType("java.util.List");
		listType.addTypeArgument(baseRecordType);
		selectByExampleByPagination.setReturnType(listType);
		StringBuilder javaDocLine = new StringBuilder();
		javaDocLine.append("/** \n"); //$NON-NLS-1$
		javaDocLine.append("\t * This method was generated by MyBatis Generator. \n"); //$NON-NLS-1$
		javaDocLine.append("\t * This method corresponds to the database table cl_personal_credit_credentials \n"); //$NON-NLS-1$
		javaDocLine.append("\t * \n"); //$NON-NLS-1$
		javaDocLine.append("\t * " + MergeConstants.NEW_ELEMENT_TAG + "\n"); //$NON-NLS-1$
		javaDocLine.append("\t */"); //$NON-NLS-1$
//		interfaze.addJavaDocLine(sb1.toString());
        selectByExampleByPagination.addJavaDocLine(javaDocLine.toString());
		interfaze.addMethod(selectByExampleByPagination);
        return true;
    }

    /**
     * select example sql
     */
	public boolean sqlMapDocumentGenerated(Document document, IntrospectedTable introspectedTable) {
		XmlElement paginationXml = new XmlElement("select");
		Attribute id = new Attribute("id", "selectByExampleByPagination");
		Attribute resultMap = new Attribute("resultMap", "BaseResultMap");
		Attribute parameterType = new Attribute("parameterType", introspectedTable.getExampleType());
		paginationXml.addAttribute(id);
		paginationXml.addAttribute(resultMap);
		paginationXml.addAttribute(parameterType);
		
		//comment
		paginationXml.addElement(new TextElement("select"));
		paginationXml.addElement(new TextElement("<!--")); //$NON-NLS-1$
        StringBuilder sb1 = new StringBuilder();
        sb1.append("  WARNING - "); //$NON-NLS-1$
        sb1.append(MergeConstants.NEW_ELEMENT_TAG);
        paginationXml.addElement(new TextElement(sb1.toString()));
        paginationXml.addElement(new TextElement("  This element is automatically generated by MyBatis Generator, do not modify.")); //$NON-NLS-1$
        paginationXml.addElement(new TextElement("-->"));
        
		XmlElement ifElement = new XmlElement("if");
        ifElement.addAttribute(new Attribute("test", "example.distinct")); 
        ifElement.addElement(new TextElement("distinct"));
        paginationXml.addElement(ifElement);

        StringBuilder sb = new StringBuilder();
        if (stringHasValue(introspectedTable
                .getSelectByExampleQueryId())) {
            sb.append('\'');
            sb.append(introspectedTable.getSelectByExampleQueryId());
            sb.append("' as QUERYID,");
            paginationXml.addElement(new TextElement(sb.toString()));
        }
        paginationXml.addElement(getBaseColumnListElement(introspectedTable));

        sb.setLength(0);
        sb.append("from ");
        sb.append(introspectedTable.getAliasedFullyQualifiedTableNameAtRuntime());
        paginationXml.addElement((new TextElement(sb.toString())));
        paginationXml.addElement(getExampleIncludeElement(introspectedTable));

        ifElement = new XmlElement("if");
        ifElement.addAttribute(new Attribute("test", "example.orderByClause != null")); 
        ifElement.addElement(new TextElement("order by ${example.orderByClause}"));
        paginationXml.addElement(ifElement);
        
        ifElement = new XmlElement("if");
        ifElement.addAttribute(new Attribute("test", "startRow != null &amp;&amp; endRow != null")); 
        ifElement.addElement(new TextElement("limit ${startRow}, ${endRow}"));
        paginationXml.addElement(ifElement);
        
        document.getRootElement().addElement(paginationXml);
        return true;
    }
    
	protected XmlElement getBaseColumnListElement(IntrospectedTable introspectedTable) {
        XmlElement baseColumnListXml = new XmlElement("include");
        baseColumnListXml.addAttribute(new Attribute("refid", introspectedTable.getBaseColumnListId()));
        return baseColumnListXml;
    }
	
	protected XmlElement getExampleIncludeElement(IntrospectedTable introspectedTable) {
        XmlElement ifElement = new XmlElement("if");
        ifElement.addAttribute(new Attribute("test", "_parameter != null")); 

        XmlElement includeElement = new XmlElement("include");
        includeElement.addAttribute(new Attribute("refid",
                introspectedTable.getMyBatis3UpdateByExampleWhereClauseId()));
        ifElement.addElement(includeElement);
        return ifElement;
    }
}
